# Generated by Django 6.0.1 on 2026-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('REMISE', 'Remise')], default='EN_ATTENTE', max_length=20),
        ),
    ]
